# Generated by Django 3.2.8 on 2021-12-11 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_category', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateName', models.CharField(max_length=50, verbose_name='Name of Date')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('locationName', models.CharField(max_length=30, verbose_name='locationName')),
                ('dateTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DateABase.datetype', verbose_name='Date Type')),
                ('date_season', models.ManyToManyField(to='DateABase.Season', verbose_name='Best Season for Date')),
                ('priceRating', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DateABase.price', to_field='price_category', verbose_name='Price')),
            ],
        ),
    ]
