# Generated by Django 3.2.8 on 2021-12-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DateABase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='priceRating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DateABase.price', verbose_name='Price'),
        ),
    ]
